name = "NeuralCodingRegistry"
uuid = "4fcc43f4-aefe-4dae-8c2d-8b2684c394d1"
repo = "https://github.com/grero/NeuralCodingRegistry.jl.git"
description = "Registry for julia code used by the NeuralCodingLab"

[packages]
0e825b22-7e33-4f72-a4cb-20e911aecd06 = { name = "CachedResults", path = "C/CachedResults" }
11ef5f8f-17ac-45eb-b004-b0dd92d25366 = { name = "GammaMixtures", path = "G/GammaMixtures" }
1fb2cab1-157b-4183-b3d5-38cecae8110a = { name = "SpiketrainGeneration", path = "S/SpiketrainGeneration" }
268555e1-3ef2-4898-9b9d-141aa6e53af3 = { name = "ParallelTransportUnfolding", path = "P/ParallelTransportUnfolding" }
275e4ca1-a518-4eac-bc9f-23cc20e68f62 = { name = "DemixedPCA", path = "D/DemixedPCA" }
3c021aa7-dcf5-4377-8829-4c53e85dfcb8 = { name = "LabeledTimeseriesTools", path = "L/LabeledTimeseriesTools" }
41fc471e-1f5c-4b2d-bbd1-04f3567f437e = { name = "LinearRegressionUtils", path = "L/LinearRegressionUtils" }
48e35133-c67d-494f-bc67-285ed7959dbe = { name = "OrthogonalLDA", path = "O/OrthogonalLDA" }
4c630530-b0df-11e8-008a-358fbd1b8883 = { name = "BehaviouralAnalysis", path = "B/BehaviouralAnalysis" }
7ebd9591-9401-448a-9f02-49877c6a7c25 = { name = "TimeResolvedDecoding", path = "T/TimeResolvedDecoding" }
94a68770-fbcf-47e0-90dc-76bcf70cf6cd = { name = "EventOnsetDecoding", path = "E/EventOnsetDecoding" }
9ccad825-6289-4415-a6ee-74c853e7b03c = { name = "TrajectoryTools", path = "T/TrajectoryTools" }
c4d60adb-60c8-55d6-9a12-9d581dce3acf = { name = "DataProcessingHierarchyTools", path = "D/DataProcessingHierarchyTools" }
c5379b7d-737a-4cf3-a598-4869b39c4869 = { name = "MDAFiles", path = "M/MDAFiles" }
c5b5f41d-6417-4974-a1bf-8957fdc17f70 = { name = "AttractorModels", path = "A/AttractorModels" }
cf94edb6-909a-5f08-bc57-c583b24583cc = { name = "RippleTools", path = "R/RippleTools" }
f62bd881-ddd8-4bde-9b42-39ec16b3efff = { name = "StandardBasisVectors", path = "S/StandardBasisVectors" }
