name = "NeuralCodingRegistry"
uuid = "4fcc43f4-aefe-4dae-8c2d-8b2684c394d1"
repo = "https://github.com/grero/NeuralCodingRegistry.jl.git"
description = "Registry for julia code used by the NeuralCodingLab"

[packages]
0e825b22-7e33-4f72-a4cb-20e911aecd06 = { name = "CachedResults", path = "C/CachedResults" }
11ef5f8f-17ac-45eb-b004-b0dd92d25366 = { name = "GammaMixtures", path = "G/GammaMixtures" }
1c0943b8-e38f-498f-b6a0-1f910535fd85 = { name = "RNNTrialStructures", path = "R/RNNTrialStructures" }
1fb2cab1-157b-4183-b3d5-38cecae8110a = { name = "SpiketrainGeneration", path = "S/SpiketrainGeneration" }
268555e1-3ef2-4898-9b9d-141aa6e53af3 = { name = "ParallelTransportUnfolding", path = "P/ParallelTransportUnfolding" }
275e4ca1-a518-4eac-bc9f-23cc20e68f62 = { name = "DemixedPCA", path = "D/DemixedPCA" }
2a85ccfc-98a0-47fa-b945-b561fd76af20 = { name = "RecurrentNetworkAnalysis", path = "R/RecurrentNetworkAnalysis" }
2ac287f9-75f0-5667-bccf-1ab644ef8eb6 = { name = "SpikeExtraction", path = "S/SpikeExtraction" }
3c021aa7-dcf5-4377-8829-4c53e85dfcb8 = { name = "LabeledTimeseriesTools", path = "L/LabeledTimeseriesTools" }
3d8592d6-65e1-5f96-8dec-2daa08481768 = { name = "StatUtils", path = "S/StatUtils" }
3d9f1ba8-ff48-11e8-3a02-0b3de68f1194 = { name = "EventRasters", path = "E/EventRasters" }
41fc471e-1f5c-4b2d-bbd1-04f3567f437e = { name = "LinearRegressionUtils", path = "L/LinearRegressionUtils" }
48e35133-c67d-494f-bc67-285ed7959dbe = { name = "OrthogonalLDA", path = "O/OrthogonalLDA" }
4c630530-b0df-11e8-008a-358fbd1b8883 = { name = "BehaviouralAnalysis", path = "B/BehaviouralAnalysis" }
5d34c7e2-af2b-5530-a1a1-19d0bbe28e18 = { name = "NeuralAnalysis", path = "N/NeuralAnalysis" }
60024d2f-e447-450b-ab68-c236a8c9f1ce = { name = "RecurrentNetworkModels", path = "R/RecurrentNetworkModels" }
70172d0b-7d6c-5685-8bb9-d866ed45e707 = { name = "TrialsAnalysis", path = "T/TrialsAnalysis" }
72b6be8f-0b79-4fcf-b71d-125970ec4fc4 = { name = "MultiDimensionalTimeSeriesPlots", path = "M/MultiDimensionalTimeSeriesPlots" }
76b9ae3e-a472-554a-ac77-032b68cfa10e = { name = "Spiketrains", path = "S/Spiketrains" }
7ebd9591-9401-448a-9f02-49877c6a7c25 = { name = "TimeResolvedDecoding", path = "T/TimeResolvedDecoding" }
83654edc-39a9-11e9-3850-750e501afe4a = { name = "Eyelink", path = "E/Eyelink" }
94a68770-fbcf-47e0-90dc-76bcf70cf6cd = { name = "EventOnsetDecoding", path = "E/EventOnsetDecoding" }
9ccad825-6289-4415-a6ee-74c853e7b03c = { name = "TrajectoryTools", path = "T/TrajectoryTools" }
ab509448-40a1-11e9-3d07-0f59fb2cbde2 = { name = "Stimulus", path = "S/Stimulus" }
b65035a2-a410-559f-91f4-51d26fe2b10d = { name = "PeriStimulusTimeHistograms", path = "P/PeriStimulusTimeHistograms" }
c4d60adb-60c8-55d6-9a12-9d581dce3acf = { name = "DataProcessingHierarchyTools", path = "D/DataProcessingHierarchyTools" }
c5379b7d-737a-4cf3-a598-4869b39c4869 = { name = "MDAFiles", path = "M/MDAFiles" }
c5b5f41d-6417-4974-a1bf-8957fdc17f70 = { name = "AttractorModels", path = "A/AttractorModels" }
cf94edb6-909a-5f08-bc57-c583b24583cc = { name = "RippleTools", path = "R/RippleTools" }
f62bd881-ddd8-4bde-9b42-39ec16b3efff = { name = "StandardBasisVectors", path = "S/StandardBasisVectors" }
